### ISSUE TITLE
表未找到

### ISSUE THREAD

**Issue by zengonly** [Wonail/wocenter#2]
![qq 20171007235600](https://user-images.githubusercontent.com/21103564/31309591-1a6049b4-abbb-11e7-877d-117dd8592081.png)

**Comment by e-kevin** [comment]
最近在更新一些重要特性以及vagrant部署开发环境，这个问题是运行`yii\web\Application()`后没有正确获取`Yii::$app->get('Wc')`导致，可以参考`backend\web\index.php`的配置。该问题已经在未发布的提交中得到解决。
